run:
  go: 1.21
  concurrency: 4
  timeout: 10m

linters:
  disable-all: true
  enable:
    # - gofmt
    # - gocritic
    # - gosimple
    # - govet
    # - ineffassign
    # - staticcheck
    # - typecheck
    # - unused
    - asciicheck
    # - depguard
    - exportloopref
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
